name: Issue Commenter

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check for bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: |
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "COMMENT_BODY=Thank you. We will fix it." >> $GITHUB_ENV
      - name: Check for feature label
        if: contains(github.event.issue.labels.*.name, 'feature')
        run: |
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "COMMENT_BODY=Thank you, we will consider to include this feature." >> $GITHUB_ENV
      - name: Check for discussion label
        if: contains(github.event.issue.labels.*.name, 'discussion')
        run: |
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "COMMENT_BODY=Thanks for starting this discussion! We welcome community input." >> $GITHUB_ENV
      - name: Add comment to issue
        if: env.COMMENT_BODY != ''
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: process.env.ISSUE_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.COMMENT_BODY
            })